// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteName =
  | 'C'
  | 'Cs'
  | 'D'
  | 'Ds'
  | 'E'
  | 'F'
  | 'Fs'
  | 'G'
  | 'Gs'
  | 'A'
  | 'As'
  | 'B';
