// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteName } from "./NoteName";

export type Note = { name: NoteName, octave: number, frequency: number, midi: number, deviation: number, };
