name: test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: src-tauri
        run: |
          cargo test --verbose
