name: Lint & Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: install frontend dependencies
        run: npm install
      - name: lint
        run: npx gts lint

  rust:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: src-tauri
        run: cargo test
